// Generated by Haxe 4.1.4
(function ($global) { "use strict";
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
Math.__name__ = true;
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
var com_blufedora_Main = function() { };
com_blufedora_Main.__name__ = true;
com_blufedora_Main.main = function() {
	var $window = window;
	$window.addEventListener("load",com_blufedora_Main.onLoad);
	$window.addEventListener("unload",com_blufedora_Main.onUnLoad);
};
com_blufedora_Main.onLoad = function() {
	var doc = window.document;
	var portfolio_container = doc.getElementById("portfolio-container");
	if(portfolio_container != null) {
		var callback = function(json_text) {
			var items = JSON.parse(json_text);
			var _g = 0;
			while(_g < items.length) {
				var item = items[_g];
				++_g;
				var folder = item.folder;
				var size = item.size;
				var brief_text = item.brief;
				var element = doc.createElement("div");
				var brief_block = doc.createElement("div");
				var brief_text_div = doc.createElement("div");
				element.classList.add("portfolio-block" + size);
				element.style.backgroundImage = "url(/portfolio/" + folder + "/thumbnail.png)";
				element.addEventListener("click",com_blufedora_Main.onPortfolioItemClicked);
				brief_text_div.innerText = brief_text;
				brief_text_div.classList.add("portfolio-brief-text");
				brief_block.appendChild(brief_text_div);
				brief_block.classList.add("portfolio-brief");
				element.appendChild(brief_block);
				brief_block.classList.add("no-select");
				if(item.url != null || item.post != null) {
					var learn_more = doc.createElement("a");
					if(item.post != null) {
						learn_more.setAttribute("href","blog-post.html?post=" + Std.string(item.post));
						learn_more.innerText = "Read Blog Post";
					} else {
						learn_more.setAttribute("href",item.url);
						learn_more.innerText = "Visit Page";
					}
					learn_more.classList.add("learn-more");
					brief_block.appendChild(learn_more);
				}
				portfolio_container.appendChild(element);
			}
		};
		var xobj = new XMLHttpRequest();
		xobj.overrideMimeType("application/json");
		xobj.open("GET","portfolio/portfolio.json",true);
		xobj.onreadystatechange = function() {
			if(xobj.readyState == 4 && xobj.status == 200) {
				callback(xobj.responseText);
			}
		};
		xobj.send(null);
	}
	var menu = doc.getElementById("menu");
	var side_panel = doc.getElementById("side_panel");
	var main_article = doc.getElementById("main_article");
	if(menu != null && side_panel != null && main_article != null) {
		var callback1 = function(evt) {
			menu.classList.toggle("opened");
			side_panel.classList.toggle("opened");
			main_article.classList.toggle("opened");
		};
		menu.onclick = callback1;
	}
};
com_blufedora_Main.onPortfolioItemClicked = function(evt) {
	var button = js_Boot.__cast(evt.currentTarget , HTMLElement);
	button.classList.toggle("opened");
};
com_blufedora_Main.onUnLoad = function() {
};
com_blufedora_Main.getFileName = function() {
	var url = window.document.location.href;
	url = url.substring(0,url.indexOf("#") == -1 ? url.length : url.indexOf("#"));
	url = url.substring(0,url.indexOf("?") == -1 ? url.length : url.indexOf("?"));
	url = url.substring(url.lastIndexOf("/") + 1,url.length);
	return url;
};
var com_blufedora_io_File = function() { };
com_blufedora_io_File.__name__ = true;
com_blufedora_io_File.loadJson = function(path,callback) {
	var xobj = new XMLHttpRequest();
	xobj.overrideMimeType("application/json");
	xobj.open("GET",path,true);
	xobj.onreadystatechange = function() {
		if(xobj.readyState == 4 && xobj.status == 200) {
			callback(xobj.responseText);
		}
	};
	xobj.send(null);
};
var haxe_Exception = function(message,previous,native) {
	Error.call(this,message);
	this.message = message;
	this.__previousException = previous;
	this.__nativeException = native != null ? native : this;
};
haxe_Exception.__name__ = true;
haxe_Exception.thrown = function(value) {
	if(((value) instanceof haxe_Exception)) {
		return value.get_native();
	} else if(((value) instanceof Error)) {
		return value;
	} else {
		var e = new haxe_ValueException(value);
		return e;
	}
};
haxe_Exception.__super__ = Error;
haxe_Exception.prototype = $extend(Error.prototype,{
	get_native: function() {
		return this.__nativeException;
	}
	,__class__: haxe_Exception
});
var haxe_ValueException = function(value,previous,native) {
	haxe_Exception.call(this,String(value),previous,native);
	this.value = value;
};
haxe_ValueException.__name__ = true;
haxe_ValueException.__super__ = haxe_Exception;
haxe_ValueException.prototype = $extend(haxe_Exception.prototype,{
	__class__: haxe_ValueException
});
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.__name__ = true;
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
	,__class__: haxe_iterators_ArrayIterator
};
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.getClass = function(o) {
	if(o == null) {
		return null;
	} else if(((o) instanceof Array)) {
		return Array;
	} else {
		var cl = o.__class__;
		if(cl != null) {
			return cl;
		}
		var name = js_Boot.__nativeClassName(o);
		if(name != null) {
			return js_Boot.__resolveNativeClass(name);
		}
		return null;
	}
};
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g = 0;
			var _g1 = o.length;
			while(_g < _g1) {
				var i = _g++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( _g ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) {
			str += ", \n";
		}
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "string":
		return o;
	default:
		return String(o);
	}
};
js_Boot.__interfLoop = function(cc,cl) {
	if(cc == null) {
		return false;
	}
	if(cc == cl) {
		return true;
	}
	var intf = cc.__interfaces__;
	if(intf != null) {
		var _g = 0;
		var _g1 = intf.length;
		while(_g < _g1) {
			var i = _g++;
			var i1 = intf[i];
			if(i1 == cl || js_Boot.__interfLoop(i1,cl)) {
				return true;
			}
		}
	}
	return js_Boot.__interfLoop(cc.__super__,cl);
};
js_Boot.__instanceof = function(o,cl) {
	if(cl == null) {
		return false;
	}
	switch(cl) {
	case Array:
		return ((o) instanceof Array);
	case Bool:
		return typeof(o) == "boolean";
	case Dynamic:
		return o != null;
	case Float:
		return typeof(o) == "number";
	case Int:
		if(typeof(o) == "number") {
			return ((o | 0) === o);
		} else {
			return false;
		}
		break;
	case String:
		return typeof(o) == "string";
	default:
		if(o != null) {
			if(typeof(cl) == "function") {
				if(js_Boot.__downcastCheck(o,cl)) {
					return true;
				}
			} else if(typeof(cl) == "object" && js_Boot.__isNativeObj(cl)) {
				if(((o) instanceof cl)) {
					return true;
				}
			}
		} else {
			return false;
		}
		if(cl == Class ? o.__name__ != null : false) {
			return true;
		}
		if(cl == Enum ? o.__ename__ != null : false) {
			return true;
		}
		return false;
	}
};
js_Boot.__downcastCheck = function(o,cl) {
	if(!((o) instanceof cl)) {
		if(cl.__isInterface__) {
			return js_Boot.__interfLoop(js_Boot.getClass(o),cl);
		} else {
			return false;
		}
	} else {
		return true;
	}
};
js_Boot.__cast = function(o,t) {
	if(o == null || js_Boot.__instanceof(o,t)) {
		return o;
	} else {
		throw haxe_Exception.thrown("Cannot cast " + Std.string(o) + " to " + Std.string(t));
	}
};
js_Boot.__nativeClassName = function(o) {
	var name = js_Boot.__toStr.call(o).slice(8,-1);
	if(name == "Object" || name == "Function" || name == "Math" || name == "JSON") {
		return null;
	}
	return name;
};
js_Boot.__isNativeObj = function(o) {
	return js_Boot.__nativeClassName(o) != null;
};
js_Boot.__resolveNativeClass = function(name) {
	return $global[name];
};
String.prototype.__class__ = String;
String.__name__ = true;
Array.__name__ = true;
var Int = { };
var Dynamic = { };
var Float = Number;
var Bool = Boolean;
var Class = { };
var Enum = { };
js_Boot.__toStr = ({ }).toString;
com_blufedora_Main.main();
})(typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
