package libBlu._enum;

/**
 * Available Shapes For Collision
 * @author Shareef Raheem (Blufedora)
 */
enum CollisionShape 
{
  CENTER;
  FULL;
  NONE;
  
  THREE_QUATERS_BOTTOM_RIGHT;
  THREE_QUATERS_BOTTOM_LEFT;
  THREE_QUATERS_TOP_RIGHT;
  THREE_QUATERS_TOP_LEFT;
  
  DIAGONAL_RIGHT;
  DIAGONAL_LEFT;
  
  HALF_BOTTOM;
  HALF_RIGHT;
  HALF_LEFT;
  HALF_TOP;
  
  QUATER_BOTTOM_RIGHT;
  QUATER_BOTTOM_LEFT;
  QUATER_TOP_RIGHT;
  QUATER_TOP_LEFT;
}